version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - MONGO_URL=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongo
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongodata: